### ISSUE TITLE
Wont work when a complete suite of elements are added

### ISSUE THREAD

**Issue by udiedrichsen** [loneleeandroo/meteor-polymerize#1]
Hi,

Very good polymer pacakges, very easy to use => Great.

I tried to add all iron and paper elements:

more bower.json 
{
  "name": "polymer",
  "private": true,
  "dependencies": {
    "webcomponentsjs": "^0.7.2",
    "polymer": "Polymer/polymer#^1.0.0",
    "iron-elements": "PolymerElements/iron-elements#~1.0.0",
    "paper-elements": "PolymerElements/paper-elements#~1.0.1"
  },
  "overrides": {
    "webcomponentsjs": {
      "main": [
        "webcomponents-lite.js"
      ]
    }
  }
}

bower install --save PolymerElements/iron-elements
bower install --save PolymerElements/paper-elements

I install all paper and iron elements, but when I start meteor, the browser is very busy and the pages dont come up.
To reproduce:

meteor create polymer
meteor add loneleeandroo:polymerize
bower install --save PolymerElements/iron-elements
bower install --save PolymerElements/paper-elements
meteor

chrome http://localhost:3000
The browser is now just spinning. The iron-elements are not the problem.

**Comment by loneleeandroo** [comment]
Hello :)

Thanks for trying out the package!

Yep I can reproduce your error. I've done a fix for it in version 0.2.2, could you give it a go to see if it works?

**Comment by udiedrichsen** [comment]
Perfect !

Works now. Good job for a sunday :+1: 
I really like Polymer 1.0
And your package is the best. Very easy, thanks a lot for fixing this so fast.

FYI:I figured out, that the iron-icons must be on top of the link list in the head to make them work in chrome, but this is already working in your package.

**Comment by loneleeandroo** [comment]
Awesome!

I kept getting new issues as I was fixing it :P I think I've fixed everything in 0.2.3 now.
