### ISSUE TITLE
Polymer and building an android apk ?

### ISSUE THREAD

**Issue by udiedrichsen** [loneleeandroo/meteor-polymerize#2]
Hi,

I dont think that this is an issue from your package, but may be you have an idea how to solve 
or how to handle this ?

https://github.com/udiedrichsen/polymer-apk-build-failed

I this repo I use your package, but this also not working with other polymer packages :-(

Maybe its an meteor issue. Its always hard to be an early bird :-)

**Comment by loneleeandroo** [comment]
Harlo :)

I don't seem to have any problems with running on android.

I started from scratch like this:

```
meteor create polymer-test
cd polymer-test
meteor add loneleeandroo:polymerize
meteor install-sdk android
meteor add-platform android
meteor run android
```

Then I stopped it and added the iron elements and it was still looking good:

```
bower install --save PolymerElements/iron-elements
meteor run android
```

I stopped it once more and added the paper elements and it was still looking good:

```
bower install --save PolymerElements/paper-elements
meteor run android
```

**Comment by udiedrichsen** [comment]
Hallo,

Yes, you are right it works on a emulator !

Please enhance you test:
mkdir ../BuildTest
meteor build ../BuildTest --server 192.168.178.53:3000

.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: The APK file for the Android build was not found.

The server ip doesnt matter, because it fails before :-)
Error: The APK file for the Android build was not found.

Running in a emulator is good, but running on a device is better.

**Comment by udiedrichsen** [comment]
I opened for this a bug in meteor:
https://github.com/meteor/meteor/issues/4544
