### ISSUE TITLE
do you have a working demo for this?

### ISSUE THREAD

**Issue by kevohagan** [loneleeandroo/meteor-polymerize#3]
seems great im just gettings issues with a normal setup

`Uncaught TypeError: flags.log.split is not a function`

**Comment by udiedrichsen** [comment]
Try my repo:
https://github.com/udiedrichsen/polymer-apk-build-failed

It a simple one. Building an android apk dont work with polymer, but I think thats a meteor issue.

**Comment by kevohagan** [comment]
thanks @udiedrichsen ill check it out! 

i didnt have problems building for android with polymer 0.5 though

**Comment by loneleeandroo** [comment]
Harlo :)

I imagine that a normal setup would involved these steps:

```
meteor create polymer-test
cd polymer-test
meteor add loneleeandroo:polymerize
meteor
```

I've just tested this as well, and i can't reproduce the error.

But I am familiar with that error xD. The <code>Uncaught TypeError: flags.log.split is not a function</code> comes from the webcomponent polyfill and it generally occurs when the load order is not correct or some html file is missing.

If you're still having issues, could you log what you see in the head tag of the document. And maybe the bower.json?

**Comment by loneleeandroo** [comment]
Can I ask if you were getting a loop of <code>Uncaught TypeError: flags.log.split is not a function</code> in your browser console?

**Comment by loneleeandroo** [comment]
If you are getting a looping <code>Uncaught TypeError: flags.log.split is not a function</code>, look at this issue: https://github.com/loneleeandroo/meteor-polymerize/issues/5
