### ISSUE TITLE
Looping Uncaught TypeError: flags.log.split is not a function

### ISSUE THREAD

**Issue by loneleeandroo** [loneleeandroo/meteor-polymerize#5]
To reproduce the issue:

```
meteor create polymer-test
cd polymer-test
meteor add loneleeandroo:polymerize@=0.2.3
meteor

bower install --save PolymerElements/iron-elements
bower install --save PolymerElements/paper-elements
meteor
```

No error messages on the server. Keep getting <code>Uncaught TypeError: flags.log.split is not a function</code> on the client.

For a temporary fix, I removed these elements:

```
"paper-checkbox": "PolymerElements/paper-checkbox#^1.0.0",
"paper-icon-button": "PolymerElements/paper-icon-button#^1.0.0"
"paper-radio-button": "PolymerElements/paper-radio-button#^1.0.0",
"paper-radio-group": "PolymerElements/paper-radio-group#^1.0.0",
"paper-tabs": "PolymerElements/paper-tabs#^1.0.0"
"paper-toggle-button": "PolymerElements/paper-toggle-button#^1.0.0"
```

**Comment by loneleeandroo** [comment]
Comment:
This issue occurs when an element is trying to import a import file, but the file is missing. A missing import causes a javascript error for Polymer, causing a loop in <code>Uncaught TypeError: flags.log.split is not a function</code>. In this case, the problem element was <code>paper-behavior</code>. Other elements were expecting a file called <code>paper-inky-focus-behavior.html</code> but the file was only added in version <code>1.0.1</code> and I had <code>1.0.0</code>. Also, in <code>paper-behaviour</code>, the main entry requires <code>paper-radio-button-behavior.html</code>, but that file does not exist anymore.

Solution:
The first step is to do a <code>bower update</code> to see if any elements were updated and files were changed. This fixed the issue for me.

If it still doesn't fix the issue, go through each element and see which one is causing the loop. When you find the elements, open the main html file and look at its imports. Check that all those imports exist.

In the future, I will check each file the element is referencing in its main file and I will throw an error if any of them are missing.

**Comment by kevohagan** [comment]
awseom @loneleeandroo !! yes i think throwing an error on dynamic check of import dependencies would be great, polymer + meteor has been notoriously difficult to work/debug with and i think this package has great ideas in it :)
